CREATE DATABASE IF NOT EXISTS dogs_db;

USE dogs_db

CREATE TABLE IF NOT EXISTS dogs(
    id INT AUTO_INCREMENT PRIMARY KEY,
    breed VARCHAR(100) NOT NULL,
    curiosity TEXT NOT NULL,
    image BLOB NOT NULL
);
