kubectl apply -f 00_namespace.yaml
kubectl apply -f 01-resourcequota.yaml
kubectl apply -f 02-mysql-secret.yaml
kubectl apply -f 03-app-configmap.yaml
kubectl apply -f 04-mysql-stateful-set.yaml
kubectl apply -f 05-mysql-headless-svc.yaml
kubectl apply -f 06-phpmyadmin-deployment.yaml
kubectl apply -f 07-phpmyadmin-svc.yaml
kubectl apply -f 08-app-deployment.yaml
kubectl apply -f 09-app-svc.yaml
kubectl apply -f 10-app-hpa.yaml
kubectl apply -f 11-ingress.yaml
kubectl apply -f 12-network.yaml